version: '3'
services:
  jenkins:
    image: bhalamish100/bjenkins
    ports:
      - "8380:8080"
      - "53000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/JENKINS_SERVER_IP:JENKINS_SERVER_IP
    environment:
      SERVER_IP: $SERVER_IP
    hostname: "${SERVER_IP}"
    networks:
      - jenkins_isolated
    restart: always

volumes:
  jenkins_home:

networks:
  jenkins_isolated:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
          gateway: 172.20.0.1
